package com.shoppit.app.domain.repository

import com.shoppit.app.domain.model.ShoppingListItem
import kotlinx.coroutines.flow.Flow

interface ShoppingListRepository {
    
    fun getShoppingList(): Flow<Result<List<ShoppingListItem>>>
    
    fun getShoppingListItem(id: Long): Flow<Result<ShoppingListItem>>
    
    suspend fun addShoppingListItem(item: ShoppingListItem): Result<Long>
    
    suspend fun addShoppingListItems(items: List<ShoppingListItem>): Result<List<Long>>
    
    suspend fun updateShoppingListItem(item: ShoppingListItem): Result<Unit>
    
    suspend fun deleteShoppingListItem(id: Long): Result<Unit>
    
    suspend fun deleteCheckedItems(): Result<Unit>
    
    suspend fun deleteAutoGeneratedItems(): Result<Unit>
    
    suspend fun uncheckAllItems(): Result<Unit>
}
